baseurl: "https://tyrian-misfits.github.io"
languageCode: "en-us"
title: "Tyrian Misfits"
theme: "book" #"xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
disablePathToLower: true
enableGitInfo: true
disableKinds: ['taxonomy', 'taxonomyTerm']

BookRepo: "https://github.com/Tyrian-Misfits/website-source"
BookEditPath: "tree/master/content"
BookDateFormat: "January 2, 2006"

permalinks:
  wvw: "/wvw/:slug/"
  announcements: "/announcements/:year/:month/:day/:slug/"

menu:
  before:
    - name: About Us
      url: "/"
      weight: 10
    - name: Announcements
      url: "/posts"
      weight: 20
    - name: Event Calendar
      url: "/calendar"
      weight: 30
  #after: []

params:
  description: "Poking holes in walls since 2012"
  footer: "Designed with ♥ by Perlkönig (Haele).<br>[Fork me on GitHub!](https://github.com/Tyrian-Misfits/website-source)"

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
