baseURL = "/"
languageCode = "en-us"
title = "Tyrian Misfits | Poking holes in walls since 2012"
theme = "xmin"

[menu]
  [[menu.main]]
    identifier = "announcements"
    name = "Announcements"
    title = "Announcements"
    url = "/announcements/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
